package runall;

public class Exception4 {
	public static void main(String[] args) {
		
	}
	public void met()
	{//throws Exception {
		try {
			wait();
		}catch(Exception e) {
			
		}
	}

}
